services:
  yt-dlp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yt-dlp-container
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    environment:
      - TZ=MST
      - VIDEO_URL=${VIDEO_URL:-}
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    command: ["python", "yt-dlp.py"]
