FROM redmine:6-bookworm

# Update packages and install dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential xz-utils \
    && rm -rf /var/lib/apt/lists/*
