# 1 Container, Using Proxy Network (External) or Isolated Network

services:
  container1:
    image: baseImage1:latest
    # build: .
    container_name: container1
    restart: always # no/on-failure/unless-stopped
    networks:
      - traefik_proxy
    # - container1_net
    # ports:
    #   - "8080:8080"
    # user: 1001:1001
    volumes:
      - .auth/:/
      - .cfg/:/
      - .data/:/
      - .log/:/
      - container1_vol1:/
      - container1_vol2:/
      # - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ENVAR=
      - ENVAR_FILE=/run/secrets/secret_1
      - ENVAR_FILE=/run/secrets/secret_2
      - ENVAR_FILE=/run/secrets/secret_3
    secrets:
      - secret_1
      - secret_2
      - secret_3
    labels:
      # Traefik Reverse Proxy
      - "traefik.http.routers.container1.rule=Host(`app.container1.xyz`)"
      - "traefik.http.routers.container1.entrypoints=web-secure"
      - "traefik.http.routers.container1.tls=true"
      - "traefik.http.routers.container1.service=container1"
      - "traefik.http.services.container1.loadbalancer.server.port=8080"
      - "traefik.http.services.container1.loadbalancer.server.scheme=http"
      # Image updates via Watchtower
      - "com.centurylinklabs.watchtower.enable=true"

secrets:
    secret_1:
      file: ./auth/secret_1.txt
    secret_2:
      file: ./auth/secret_2.txt
    secret_3:
      file: ./auth/secret_3.txt

networks:
  traefik_proxy:
    external: true

  container1_net: # Comment out if using proxy network
    name: container1_net
    driver: bridge

volumes:
  container1_vol1:
    name: container1_vol1
    driver: local

  container1_vol2:
    name: container1_vol2
    driver: local
