services:
  secretscanner-img:
    image: quay.io/deepfenceio/deepfence_secret_scanner_ce:2.2.0
    container_name: secretscanner-img
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: [
      "-image-name", "quay.io/deepfenceio/deepfence_secret_scanner_ce:2.2.0",
      "--output", "json"
    ]
    stdin_open: true
    tty: true
    restart: "no"
