services:
  linkstack:
    image: linkstackorg/linkstack:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - linkstack_data:/htdocs

volumes:
  linkstack_data:
