---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- group_1:
    - Calendar:
        href:
        description:
        widget:
            type: calendar
            firstDayInWeek: sunday # optional - defaults to monday
            view: monthly # optional - possible values monthly, agenda
            maxEvents: 10 # optional - defaults to 10
