services:
  postgres:
    image: postgres:17.0-bookworm
    container_name: postgres_demo
    restart: always
    networks:
      - postgres_demo
    volumes:
      - ./auth:/run/secrets
      - ./data:/var/lib/postgresql/data
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRES_DB_FILE=/run/secrets/pg_db
      - POSTGRES_USER_FILE=/run/secrets/pg_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_pw
    secrets:
      - pg_db
      - pg_user
      - pg_pw

secrets:
    pg_db:
      file: ./auth/pg_db.txt
    pg_user:
      file: ./auth/pg_user.txt
    pg_pw:
      file: ./auth/pg_pw.txt

networks:
  postgres_demo:
    driver: bridge
